# Exercise 1

In [1]:
import numpy as np


my_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
my_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Exercice 2

In [63]:

liste = [3.14, 2.17, 0, 1, 2]

array = np.array(liste).astype(int)

array

array([3, 2, 0, 1, 2])

# Exercice 3

In [3]:
array = np.arange(0, 9).reshape(3, 3)

array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Exercice 4

In [7]:
array_2D = np.random.rand(4, 5)
array_2D

array([[0.24514083, 0.30752575, 0.61791326, 0.02148742, 0.30403298],
       [0.79574825, 0.56260722, 0.52691261, 0.34594192, 0.72565133],
       [0.91787889, 0.75514657, 0.53349041, 0.83217013, 0.71781483],
       [0.14939146, 0.73901294, 0.6250442 , 0.17065548, 0.98046367]])

# Exercice 5

In [8]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])

In [14]:
array[1, 0:]

array([20, 21, 22, 23, 24])

# Exercice 6

In [41]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

# Exercice 7

In [44]:
matrix_one = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0 , 0, 1, 0],  [0 , 0, 0, 1]])
matrix_one

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [45]:
matrix_1 = np.eye(4)
matrix_1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Exercice 8

In [50]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("sum :", array.sum(),", Avreage :",array.mean())

sum : 45 , Avreage : 5.0


# Exercice 9

In [53]:
array = np.arange(1, 21).reshape(4, 5)
array


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# Exercie 10

In [61]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

odd_numbers = []

for i in array:
    if i % 2 != 0:
        odd_numbers.append(i)

array = np.array(odd_numbers)

print(array)


[1 3 5 7 9]
